### ISSUE TITLE
Packer vagrant-cloud postprocessor fails when checking available box versions

### ISSUE THREAD

**Issue by GR360RY** [dlundgren/phagrancy#12]
## Environment
Docker Compose

## Issue
vagrant-cloud postprocessor fails when attempting to validate versions:

```
==> virtualbox-vm (vagrant-cloud): Creating version: 0.1.0
2020/05/17 17:22:56 packer-post-processor-vagrant-cloud plugin: Post-Processor Vagrant Cloud API POST: http://127.0.0.1/api/v1/box/devops/macos-catalina/versions.
2020/05/17 17:22:56 packer-post-processor-vagrant-cloud plugin:
2020/05/17 17:22:56 packer-post-processor-vagrant-cloud plugin:  Body: {"version":{"version":"0.1.0"}}
2020/05/17 17:22:56 packer-post-processor-vagrant-cloud plugin: Post-Processor Vagrant Cloud API Response:
2020/05/17 17:22:56 packer-post-processor-vagrant-cloud plugin:
2020/05/17 17:22:56 packer-post-processor-vagrant-cloud plugin: &{Status:405 Method Not Allowed StatusCode:405 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Allow:[POST] Connection:[keep-alive] Content-Length:[556] Content-Type:[text/html;charset=UTF-8] Date:[Sun, 17 May 2020 14:22:56 GMT] Server:[nginx] X-Powered-By:[PHP/7.3.18]] Body:0xc00061a200 ContentLength:556 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc0001a8300 TLS:0xc00015a0b0}
==> virtualbox-vm (vagrant-cloud): error decoding error response: invalid character '<' looking for beginning of value
==> virtualbox-vm (vagrant-cloud): Error creating version:
==> virtualbox-vm (vagrant-cloud): Step "stepCreateVersion" failed
```

Packer postprocessors configuration:
```json
  "post-processors": 
    [
        [
            {
            "type": "vagrant",
            "output": "{{user `vagrant_box_directory`}}/packer_{{.BuildName}}_{{.Provider}}.box"
            },
            {
                "type": "vagrant-cloud",
                "box_tag": "devops/macos-catalina",
                "vagrant_cloud_url": "http://127.0.0.1/api/v1",
                "insecure_skip_tls_verify": true,
                "access_token": "",
                "version": "0.1.0"
            }
        ]
    ],
```

Server logs:
```
phagrancy-nginx | 172.19.0.1 - - [17/May/2020:14:22:56 +0000] "POST /api/v1/box/devops/macos-catalina/versions HTTP/1.1" 301 162 "-" "Go-http-client/1.1"
phagrancy-php-fpm | 172.19.0.2 -  17/May/2020:14:22:56 +0000 "GET /index.php" 405
phagrancy-nginx | 172.19.0.1 - - [17/May/2020:14:22:56 +0000] "GET /api/v1/box/devops/macos-catalina/versions HTTP/1.1" 405 556 "http://127.0.0.1/api/v1/box/devops/macos-catalina/versions" "Go-http-client/1.1" "-"
```

Any chance the API is changed recently and this is yet to be supported ?

**Comment by dlundgren** [comment]
Thanks for reporting this, I'll take a look.

**Comment by GR360RY** [comment]
Thanks, David. I can assist with updating the wiki to reflect the recent changes in the way the vagrant-cloud postprocessor works. Will merge request work for you ?

**Comment by dlundgren** [comment]
I tested in a non-Docker environment and the vagrant-cloud postprocessor is working properly.

I'll be testing in a Docker environment next

**Comment by timblaktu** [comment]
Hello @dlundgren, @GR360RY I'm just curious where this issue ended up? Thanks.

**Comment by dlundgren** [comment]
Due to several projects, I've not had time to circle back to testing this via Docker.

Thanks for reminding me.

I completely missed the configuration option in the post-processor, `"vagrant_cloud_url": "http://127.0.0.1/api/v1",` should be `"vagrant_cloud_url": "https://127.0.0.1/api/v1",`

The [nginx.conf](https://github.com/dlundgren/phagrancy/blob/master/docker/nginx/nginx.conf) that we are shipping redirects http to https. This explains the 301, and the subsequent 405.

If the issue persists after changing to https, or you change the nginx.conf to serve the app on port 80, please let me know and I can take a further look. I was able to spin up the Docker environment, and a test build was successfully completed and uploaded.

**Comment by GR360RY** [comment]
@dlundgren , thanks I will check it out and update!
