### ISSUE TITLE
works with vagrant-cloud?

### ISSUE THREAD

**Issue by FrankVanDamme** [dlundgren/phagrancy#15]
Hi! 
It looks like the Atlas post processor changed into vagrant-cloud post processor (the info on it is a bit sparse but the packer docs mention that the ATLAS_TOKEN env. variable is still accepted as a source of auth token). Alas, this thing tries to connect to connect to /authenticate on Phagrancy. Could it be that the vagrant-cloud api just has different endpoints? Can Phagrancy still be made to work with it?

**Comment by dlundgren** [comment]
The documentation was not updated to reflect `vagrant-cloud` usage, but I've been using it successfully.

I've updated the [Usage with Packer and Vagrant](/dlundgren/phagrancy/wiki/Usage-with-Packer-and-Vagrant#vagrant-cloud-post-processor)
