### ISSUE TITLE
Docker workflow problems

### ISSUE THREAD

**Issue by roynielsen17** [dlundgren/phagrancy#16]
Docker workflow on the wiki doesn't work for me - either command for building the php-fpm container in the docker/README.md

```
docker % docker build -t phagrancy-php-fpm:latest php-fpm
[+] Building 1.0s (4/4) FINISHED                                                               
 => [internal] load build definition from Dockerfile                                      0.0s
 => => transferring dockerfile: 153B                                                      0.0s
 => [internal] load .dockerignore                                                         0.0s
 => => transferring context: 2B                                                           0.0s
 => CANCELED [internal] load metadata for docker.io/library/php:7.3-fpm-buster            1.0s
 => ERROR [internal] load metadata for docker.io/library/phagrancy-nginx:latest           1.0s
------
 > [internal] load metadata for docker.io/library/phagrancy-nginx:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
rsn5133@penxfalcon docker % docker build -t phagrancy-php-fpm:latest php-fpm
[+] Building 0.9s (4/4) FINISHED                                                               
 => [internal] load build definition from Dockerfile                                      0.0s
 => => transferring dockerfile: 36B                                                       0.0s
 => [internal] load .dockerignore                                                         0.0s
 => => transferring context: 2B                                                           0.0s
 => CANCELED [internal] load metadata for docker.io/library/php:7.3-fpm-buster            0.8s
 => ERROR [internal] load metadata for docker.io/library/phagrancy-nginx:latest           0.8s
------
 > [internal] load metadata for docker.io/library/phagrancy-nginx:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

I get the following error when attempting to build the php-fpm directory - 

```
 php-fpm % docker build .
[+] Building 0.7s (4/4) FINISHED                                                               
 => [internal] load build definition from Dockerfile                                      0.0s
 => => transferring dockerfile: 153B                                                      0.0s
 => [internal] load .dockerignore                                                         0.0s
 => => transferring context: 2B                                                           0.0s
 => CANCELED [internal] load metadata for docker.io/library/php:7.3-fpm-buster            0.6s
 => ERROR [internal] load metadata for docker.io/library/phagrancy-nginx:latest           0.6s
------
 > [internal] load metadata for docker.io/library/phagrancy-nginx:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

I was able to build the nginx container from the README.md file, and for the nginx directory.

Do you have a recommendation for getting past this error?

Respectfully,
-Roy Nielsen

**Comment by dlundgren** [comment]
I updated the dockerfile for nginx to use `nginx:1.20.0`, and I was able to get both images built.

Could try pulling the repo and building again?

**Comment by roynielsen17** [comment]
Awesome!  - they both built.

Followed the directions, it looks like it's running, however getting an
error when I attempted to go to http://localhost and http://127.0.0.1

[image: image.png]

firefox and brave browsers

and just got a blank page on https://localhost, or https://127.0.0.1 after
"accepting the risk" of a self signed cert... But that would only get that
far on Firefox.


Respectfully,
-Roy Nielsen

**Comment by dlundgren** [comment]
Visiting https://127.0.0.1 and getting a white screen is expected, that page returns nothing.

if you look at the logs for the phagrancy-php-fpm image, you should have a log line when visiting that URL.

`"GET /index.php" 200`

**Comment by roynielsen17** [comment]
Hello,

Got the 200 - so it's installed - what's next?  How do I use the system?
Is it only available via command line - like curl, or packer or vagrant?

Respectfully,
-Roy Nielsen

**Comment by dlundgren** [comment]
I use it with [Packer & Vagrant](https://github.com/dlundgren/phagrancy/wiki/Usage-with-Packer-and-Vagrant)

**Comment by roynielsen17** [comment]
Sounds good, Thank you -

Respectfully,
-Roy Nielsen
505-412-9204
https://linkedin.com/in/roynielsen17

HPC Development Engineer - Engineering next generation Supercomputer
Infrastructure for Penn State University

Volunteer Primary Automation Architect, open source
https://github.com/clockworksspheres projects, meta project -
https://github.com/clockworksspheres/IoTHarborAnywhere/wiki


*The journey of a thousand miles begins with a single step.*

*- Lao Tzu*

******************************************************************************************
CONFIDENTIALITY NOTICE: This E-mail (including attachments) is covered by
the Electronic Communications Privacy Act, 18 U.S.C. 2210-2521, is
confidential and may be legally privileged. This E-mail contains
information that is private, confidential, or is protected by
the attorney-client work product doctrines, and is intended only for the
use of the individual(s) named herein. If you are not the intended
recipient, be advised that unauthorized use, disclosure, copying,
distribution, or the taking of any action in reliance on this information
is strictly prohibited. If you have received this E-mail in error, please
immediately notify the sender by replying to this E-mail, and delete the
original message and any attachments. Thank you.
******************************************************************************************
