### ISSUE TITLE
Hidden semantic version error

### ISSUE THREAD

**Issue by syntacticvexation** [dlundgren/phagrancy#6]
If I upload a box without semantic versioning - i.e. 22 instead of 22.0.0, according to the code the API should return "must be semantically versioned" however I get a 404 returned:
`    <head>
        <title>Page Not Found</title>
        <style>
            body{
                margin:0;
                padding:30px;
                font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;
            }
            h1{
                margin:0;
                font-size:48px;
                font-weight:normal;
                line-height:48px;
            }
            strong{
                display:inline-block;
                width:65px;
            }
        </style>
    </head>
    <body>
        <h1>Page Not Found</h1>
        <p>
            The page you are looking for could not be found. Check the address bar
            to ensure your URL is spelled correctly. If all else fails, you can
            visit our home page at the link below.
        </p>
        <a href='http:/localhost/'>Visit the Home Page</a>
    </body>
</html>
`

This is the case with using either nginx or Apache.

**Comment by dlundgren** [comment]
Thanks for the report, I will be looking at this and other issues over the next few days.

I think changing the error message is also a good idea, as vagrantcloud.com allows a relaxed SemVer scheme to be used.

**Comment by dlundgren** [comment]
This should be fixed now.

The version check is based on https://www.vagrantup.com/docs/boxes/versioning.html#version-constraints, and my own testing of creating versions in vagrant-cloud UI.

**Comment by syntacticvexation** [comment]
I can confirm that Phagrancy accepts 22 now but when I perform a box update I get the following error from Vagrant:
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/pathname.rb:409:in `initialize': no implicit conversion of Integer into String (TypeError)

22.0 works fine though.
