### ISSUE TITLE
Is there a Docker image?

### ISSUE THREAD

**Issue by madeinoz67** [dlundgren/phagrancy#7]
Is there a docker image for this project anywhere?

**Comment by dlundgren** [comment]
I have not created one, but I can put it on the roadmap to do so. Please send a PR for a Docker image if you need one sooner.

**Comment by syntacticvexation** [comment]
I have a puppet module that documents the setup for Debian if this would assist with image development.

**Comment by madeinoz67** [comment]
@syntacticvexation sounds great as I've just started writing an ansible role as once I have this finished I want to look at incorporating a prometheus exporter into the service using the prometheus php client which should give a view into the repository as well as service monitoring / alerting.

**Comment by madeinoz67** [comment]
have added the prometheus exporter as a request in #8

**Comment by madeinoz67** [comment]
@syntacticvexation I've got some time to work back on this, do you have a link to a repo for the puppet module you mentioned above?

**Comment by syntacticvexation** [comment]
No worries.

https://github.com/syntacticvexation/puppet-phagrancy

**Comment by madeinoz67** [comment]
many thanks @syntacticvexation
